# Generated by Django 3.1.2 on 2020-10-12 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('url_github', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='')),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
